#pragma once

#ifndef __ASSEMBLER__

enum mid1_keycodes {
    FOCUS_TOGGLE,
    FOCUS_RESET,
    FOCUS_MODE_NEXT,
    FOCUS_WORK_DEC,
    FOCUS_WORK_INC,
    FOCUS_BREAK_DEC,
    FOCUS_BREAK_INC,

    LED_CONTROLLER_LAYER_DEC,
    LED_CONTROLLER_LAYER_INC,
    LED_CONTROLLER_PARAM_DEC,
    LED_CONTROLLER_PARAM_INC,
    LED_EDIT_HUE,
    LED_EDIT_SAT,
    LED_EDIT_VAL,
    LED_EDIT_ANIM,
};

#endif
