#pragma once

#ifndef __ASSEMBLER__

enum mid1_keycodes {
    FOCUS_TOGGLE,
    FOCUS_RESET,
    FOCUS_MODE_NEXT,
    FOCUS_WORK_DEC,
    FOCUS_WORK_INC,
    FOCUS_BREAK_DEC,
    FOCUS_BREAK_INC,

    LED_CONTROLLER_LAYER_DEC,
    LED_CONTROLLER_LAYER_INC,
    LED_CONTROLLER_HUE_DEC,
    LED_CONTROLLER_HUE_INC,
    LED_CONTROLLER_SAT_DEC,
    LED_CONTROLLER_SAT_INC,
    LED_CONTROLLER_ANIM_DEC,
    LED_CONTROLLER_ANIM_INC,
    LED_CONTROLLER_RESET,
    LED_CONTROLLER_BOOT_TOG,
    LED_CONTROLLER_BOOT_PLAY,
};

#endif
